// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePosition'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateStaff(arg1, arg2) {
  return window['go']['main']['App']['CreateStaff'](arg1, arg2);
}

export function DeletePosition(arg1) {
  return window['go']['main']['App']['DeletePosition'](arg1);
}

export function DeleteStaff(arg1) {
  return window['go']['main']['App']['DeleteStaff'](arg1);
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetStaff() {
  return window['go']['main']['App']['GetStaff']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdatePosition(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdatePosition'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateStaff(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStaff'](arg1, arg2, arg3);
}
