// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreatePosition(arg1:string,arg2:any,arg3:any,arg4:any,arg5:any):Promise<models.Position>;

export function CreateStaff(arg1:string,arg2:number):Promise<models.StaffWithPosition>;

export function DeletePosition(arg1:number):Promise<boolean>;

export function DeleteStaff(arg1:number):Promise<boolean>;

export function GetPositions():Promise<Array<models.Position>>;

export function GetStaff():Promise<Array<models.StaffWithPosition>>;

export function Greet(arg1:string):Promise<string>;

export function UpdatePosition(arg1:number,arg2:string,arg3:any,arg4:any,arg5:any,arg6:any):Promise<models.Position>;

export function UpdateStaff(arg1:number,arg2:string,arg3:number):Promise<models.StaffWithPosition>;
